export const startingDeck = [
  {
    name: "GalaxyGuppy",
    boardSlot: 1,
    attack: true,
    attackAction: { shells: 1 },
    defenseAction: { shells: 1 },
  },
  {
    name: "CommetCrab",
    boardSlot: 2,
    attack: true,
    attackAction: { shells: 1 },
    defenseAction: { shells: 1 },
  },
  {
    name: "StarSquid",
    boardSlot: 3,
    attack: true,
    attackAction: { shells: 1 },
    defenseAction: { shells: 1 },
  },
  {
    name: "LunaFlare",
    boardSlot: 4,
    attack: true,
    attackAction: { shells: 1 },
    defenseAction: { shells: 1 },
  },
  {
    name: "Mystdrift",
    boardSlot: 5,
    attack: true,
    attackAction: { shells: 1 },
    defenseAction: { shells: 1 },
  },
  {
    name: "LuminaLobster",
    boardSlot: 6,
    attack: true,
    attackAction: { shells: 1 },
    defenseAction: { shells: 1 },
  },
  {
    name: "ViperFish",
    boardSlot: 7,
    attack: true,
    attackAction: { shells: 3 },
    defenseAction: { shells: 2 },
  },
  {
    name: "CosmicPenguin",
    boardSlot: 8,
    attack: true,
    attackAction: { shells: 3 },
    defenseAction: { shells: 2 },
  },
  {
    name: "EclipseEel",
    boardSlot: 9,
    attack: true,
    attackAction: { corals: 10 },
    defenseAction: { shells: 3 },
  },
  {
    name: "RocketShrimp",
    boardSlot: 10,
    attack: true,
    attackAction: { corals: 10 },
    defenseAction: { shells: 3 },
  },
  {
    name: "CelesPiranha",
    boardSlot: 11,
    attack: true,
    attackAction: { corals: 10 },
    defenseAction: { shells: 4 },
  },
  {
    name: "KrystalHermit",
    boardSlot: 12,
    attack: true,
    attackAction: { corals: 10 },
    defenseAction: { shells: 5 },
  },
]
