export const startingDeck = [
  {
    name: "card1",
    boardSlot: 1,
    attack: true,
    attackAction: { shells: 1 },
    defenseAction: { shells: 1 },
  },
  {
    name: "card2",
    boardSlot: 2,
    attack: true,
    attackAction: { shells: 1 },
    defenseAction: { shells: 1 },
  },
  {
    name: "card3",
    boardSlot: 3,
    attack: true,
    attackAction: { shells: 1 },
    defenseAction: { shells: 1 },
  },
  {
    name: "card4",
    boardSlot: 4,
    attack: true,
    attackAction: { shells: 1 },
    defenseAction: { shells: 1 },
  },
  {
    name: "card5",
    boardSlot: 5,
    attack: true,
    attackAction: { shells: 1 },
    defenseAction: { shells: 1 },
  },
  {
    name: "card6",
    boardSlot: 6,
    attack: true,
    attackAction: { shells: 1 },
    defenseAction: { shells: 1 },
  },
  {
    name: "card7",
    boardSlot: 7,
    attack: true,
    attackAction: { shells: 3 },
    defenseAction: { shells: 2 },
  },
  {
    name: "card8",
    boardSlot: 8,
    attack: true,
    attackAction: { shells: 3 },
    defenseAction: { shells: 2 },
  },
  {
    name: "card9",
    boardSlot: 9,
    attack: true,
    attackAction: { corals: 1 },
    defenseAction: { shells: 3 },
  },
  {
    name: "card10",
    boardSlot: 10,
    attack: true,
    attackAction: { corals: 1 },
    defenseAction: { shells: 3 },
  },
  {
    name: "card11",
    boardSlot: 11,
    attack: true,
    attackAction: { corals: 1 },
    defenseAction: { shells: 4 },
  },
  {
    name: "card12",
    boardSlot: 12,
    attack: true,
    attackAction: { corals: 1 },
    defenseAction: { shells: 5 },
  },
]
